### ISSUE TITLE
Sua integração com Excel é muito boa...

### ISSUE THREAD

**Issue by cicerocruz** [dan-atilio/AdvPL#1]
Olá fiz algumas  alterações na sua  classe...

Dúvida, como você faria a manipulação de outras  abas? É que  vou ter que  implementar isso... :) 

O meu único problema  atual é não poder colocar  imagem no xml... de resto sua  implementação é  fantastica

[zExcelXML-1.0.zip](https://github.com/dan-atilio/AdvPL/files/1885975/zExcelXML-1.0.zip)

**Comment by dan-atilio** [comment]
No caso das abas, se forem tabelas diferentes e campos diferentes, acho que é só usar outros nomes para a manipulação das variáveis.
No caso da imagem, eu tentei procurar também, e não achei suporte a xml com imagem no excel, se encontrar algo, me avisa.
Abraços.
