### ISSUE TITLE
Função zChooseFile

### ISSUE THREAD

**Issue by jefersonlemos** [dan-atilio/AdvPL#3]
Olá, eu estou iniciando no advpl e gostaria de entender qual o objetivo dessa função. Pode explicar ?

Pode também explicar porque usa PowerShell dentro do AdvPL ?

Muito Obrigado

**Comment by siga0984** [comment]
Opa, beleza ? Então ... pelo que eu entendi do fonte, essa função serve apenas para plataformas Windows, e ela cria um arquivo de lote ( batch ) com comandos do PowerShell, para abrir uma janela de diálogo do Windows para você escolher um determinado arquivo, e ao escolhê-lo, o script do powershell grava o nome do arquivo escolhido em outro arquivo, que é lido pelo AdvPL e é retornado... Esse fonte é apenas uma forma totalmente diferente -- e sem usar nenhuma interface gráfica do AdvPL -- para abrir uma caixa de diálogo no sistema operacional e permitir o usuário / operador escolher um arquivo do disco em uma determinada pasta, e retornar para o código AdvPL o nome do arquivo escollhido ... :P

**Comment by siga0984** [comment]
No Advpl , a função memowrite() é usada para criar um "bat" no disco, a wairtun() para fazer um shell para o sistema operacional pelo SmartClient para rodar esse bat, e a memoread() é usada para ler o resultado que o script gravou no arquivo "resultado.txt" ... o AdvPL tem função nativa para abrir uma caixa de diálogo ( multi-plataforma) para escolher arquivo ou pasta, sem fazer shell... chama-se cGetFile()

**Comment by dan-atilio** [comment]
Olá Jeferson, obrigado pelo interesse no fonte, e obrigado Julio pelas contribuições também.

Esse fonte eu criei, pois a cGetFile() é muito antiga e segundo os usuários, eles se confundiam ao encontrar a pasta e os arquivos, inclusive o print da tela e a explicação estão nesse artigo: https://terminaldeinformacao.com/2017/11/21/funcao-para-selecionar-arquivos-windows-explorer-utilizando-advpl/

Basicamente é criar um arquivo batch com instruções em powershell para abrir uma tela de navegação no sistema operacional para assim escolher um arquivo.

A TOTVS criou uma função nova em 2020, chamada tFileDialog ( https://tdn.totvs.com/display/tec/tFileDialog ), que funciona também em outros sistemas operacionais (já preparei um artigo para o Terminal de Informação que irá ao ar daqui algumas semanas).

Qualquer dúvida, é só entrar em contato.
