### ISSUE TITLE
Tem como compatibilizar este fonte zCadSX6.prw para o dicionário de dados no banco de dados?

### ISSUE THREAD

**Issue by paulomarcelo** [dan-atilio/AdvPL#4]
Tem como compatibilizar este fonte zCadSX6.prw para o dicionário de dados no banco de dados?
https://github.com/dan-atilio/AdvPL/blob/master/Projetos/Dicion%C3%A1rio%20de%20Dados/zCadSX6.prw

**Comment by dan-atilio** [comment]
Eu não compatibilizei, na verdade eu descontinuei esse código, pois a TOTVS não permite mais a manipulação de dicionário diretamente devido as diretivas de boas práticas.
Caso você deseja alterar parâmetros, ainda existe a PutMV - https://tdn.totvs.com/pages/releaseview.action?pageId=22479602
